# Global defaults for queued video jobs (overridden by .env UPLOADER_DEFAULT_*)
defaults:
  privacy: private
  is_short: false
  category_id: "10"
  made_for_kids: false
  language: en
  tags: []   # no tags unless you set them per video or per channel

channels:
- id: justcavefire
  name: Cavefire
  youtube_channel_id: UCAKbpNSZFZ7hYPjuUOOA9bQ
  token_path: s3://youtuber-uploader/secrets/justcavefire/youtube_token.json
  registry_path: s3://youtuber-uploader/state/justcavefire/upload_registry.txt
  category_id: '10'
  default_tags: []
  made_for_kids: false
  publish:
    timezone: America/New_York
    hour: 9
    interval_hours: 24.0
  custom_url: '@justcavefire'
- id: mmmactually
  name: Erm Actually
  youtube_channel_id: UCzwG8QFCn0XbdgMcDbDVSRg
  token_path: s3://youtuber-uploader/secrets/mmmactually/youtube_token.json
  registry_path: s3://youtuber-uploader/state/mmmactually/upload_registry.txt
  category_id: '10'
  default_tags: []
  made_for_kids: false
  publish:
    timezone: America/New_York
    hour: 9
    interval_hours: 24.0
  custom_url: '@mmmactually'
google:
  oauth_port: 8080
