channels:
- id: justcavefire
  name: Cavefire
  youtube_channel_id: UCAKbpNSZFZ7hYPjuUOOA9bQ
  token_path: s3://youtuber-uploader/secrets/justcavefire/youtube_token.json
  registry_path: s3://youtuber-uploader/state/justcavefire/upload_registry.txt
  category_id: '10'
  default_tags: []
  made_for_kids: false
  publish:
    timezone: America/New_York
    hour: 9
    interval_hours: 24.0
  custom_url: '@justcavefire'
- id: mmmactually
  name: Erm Actually
  youtube_channel_id: UCzwG8QFCn0XbdgMcDbDVSRg
  token_path: s3://youtuber-uploader/secrets/mmmactually/youtube_token.json
  registry_path: s3://youtuber-uploader/state/mmmactually/upload_registry.txt
  category_id: '10'
  default_tags: []
  made_for_kids: false
  publish:
    timezone: America/New_York
    hour: 9
    interval_hours: 24.0
  custom_url: '@mmmactually'
- id: yourdopaminerat
  name: Dopamine Rat
  youtube_channel_id: UC9fwC1kxFt_PhRNnX09Y0Fw
  token_path: s3://youtuber-uploader/secrets/yourdopaminerat/youtube_token.json
  registry_path: s3://youtuber-uploader/state/yourdopaminerat/upload_registry.txt
  category_id: '10'
  default_tags: []
  made_for_kids: false
  publish:
    timezone: America/New_York
    hour: 9
    interval_hours: 24.0
  custom_url: '@yourdopaminerat'
- id: nappabeats
  name: "NappaBeats \uBC30\uCD94"
  youtube_channel_id: UC1OtKf3lvaMMJAMikp3cHOA
  token_path: s3://youtuber-uploader/secrets/nappabeats/youtube_token.json
  registry_path: s3://youtuber-uploader/state/nappabeats/upload_registry.txt
  category_id: '10'
  default_tags: []
  made_for_kids: false
  publish:
    timezone: America/New_York
    hour: 9
    interval_hours: 24.0
  custom_url: '@nappabeats'
google:
  oauth_port: 8080
